### ISSUE TITLE
TODO LIST

### ISSUE THREAD

**Issue by TexelBox** [TexelBox/cpp-xplatform#10]
# This issue board is reserved as an area for my general todo list

**Comment by TexelBox** [comment]
### Features / Enhancements
- [x] **USE 'project-name' AND 'project_name' AS IDENTIFIERS**
- [ ] **MIGRATE TO CMAKE 3.16 AND REMOVE COTIRE / REPLACE PARTS OF SCRIPTS WITH MORE MODERN METHODS**
- [ ] **MAKE SURE EXTERNAL-TESTS TARGET PROPERTIES ARE CONSISTENT WITH MAIN TARGET**
- [ ] **ADD SEMANTIC VERSIONING SUPPORT / "--version"**
- [ ] **CHANGE PROJECT STRUCTURE TO BE MORE INTUITIVE TO ADD NEW SCRIPTS THAT DO NOT CONFLICT IN BUILD OUTPUT**
- [ ] **ADD USER BUILD SCRIPTS**
- [ ] **ADD SCRIPTS FOR VS2019**
- [ ] **ADD SCRIPTS FOR GCC/CLANG FORCING**
- [ ] **ADD MORE COMPILER VERSIONS TO CI CONFIGS**
- [ ] **CLEANUP/SIMPLIFY ALL FILES (ESPECIALLY THE CI SCRIPTS)**
- [ ] **ADD PROJECT RENAME SCRIPT(S)**
- [ ] **ADD THE ISSUE/PR/etc. TEMPLATES**
- [ ] **FIX ALL COMPILER WARNINGS IN THE SAMPLE CODE**
- [ ] **ADD PROJECT SETUP PROCESS**
- [ ] **ADD MORE DOCUMENTATION**
- [ ] **ADD OPTION FOR SETTING MSVC SUBSYSTEM TO WINDOWS TO HIDE CONSOLE FOR GUI APPS**
- [ ] **ADD DLL COPYING / SHARED LIBRARY SUPPORT**
- [ ] **ADD CCACHE SUPPORT**
- [ ] **ADD BETTER SUPPORT FOR BUILDING LIBRARY TARGETS**

**Comment by TexelBox** [comment]
### Documentation / FAQ
- [x] **.**
